version: '3.8'
services:
  mapproxy_DEV:
    # network_mode: host
    image: ghcr.io/mapproxy/mapproxy/mapproxy:6.0.1-nginx
    container_name: mapproxy_DEV
    ports:
      - "${PORT_NUMBER}:80"
    volumes:
      - ./mapproxy.yaml:/mapproxy/config/mapproxy.yaml:ro
      - ./World_Mask_900913.geojson:/mapproxy/config/World_Mask_900913.geojson:ro
      - ./cache_data:/mapproxy/config/cache_data
